name: 'IND'
on:
  schedule:
    - cron: '25 19 * * *'
  workflow_dispatch:

jobs:
  s:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: |
          e(){echo "$@";}
          e "GC:";e " R:${{github.repository}}";e " F:${{github.ref}}";e " E:${{github.event_name}}"
          e "T:";e " U:$(date -u)";e " K:$(TZ=A/S date)"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          pwd;ls -la;e "P:";ls -la *p/||e "*p !"
      - run: |
          C=$(find _posts/ -name "*.md" -mtime -1 -type f)
          [ ! -z "$C" ]&&{
            e "F:";e "$C"
            L="[";declare -A s
            for f in $C;do
              N=$(basename "$f")
              P=$(echo "$N"|sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//'|sed 's/--/-/g'|sed 's/\.md$//'|sed 's/-$//')
              BASE="${{secrets.REPO_URL}}"
              U="https://$BASE/shopping/$P/"
              [ -z "${s[$U]}" ]&&{s[$U]=1;L="$L\"$U\",";e "P:$U";}
            done
            L="${L%,}]"
            e "S:";echo $L|grep -o '"https://[^"]*"'|head -n 1
            r=$(curl -s -w "\nS:%{http_code}" -X POST "https://api.indexnow.org/indexnow"\
            -H "C:application/json"\
            -d "{\"h\":\"$BASE\",\"k\":\"${{secrets.INDEXNOW_KEY}}\",\"u\":$L,\"l\":\"https://$BASE/${{secrets.INDEXNOW_KEY}}.txt\"}")
            e "R:";e "$r"
            echo "$r"|grep -q "S:200"&&{e "OK!";}||{e "ERR";exit 1;}
          }||e "No *.md < 24h"
      - if: always()
        run: |
          [ "${{job.status}}"="success" ]&&e "✅"||e "❌"
          e "W:$(date)"
