name:'I'
on:{schedule:[{cron:'25 19 * * *'}],workflow_dispatch:null}
jobs:
  s:
    runs-on:ubuntu-latest
    permissions:{contents:read}
    steps:
      - run:|
          e(){echo "$@";}
          e "GC:";e " R:${{g.r}}";e " F:${{g.f}}";e " E:${{g.e}}";e "T:";e " U:$(date -u)";e " K:$(TZ=A/S date)"
      - uses:actions/checkout@v4
        with:{fetch-depth:0}
      - run:|
          pwd;ls -la;e "P:";ls -la *p/||e "*p !"
      - run:|
          C=$(find _p/ -name "*.md" -mtime -1 -type f)
          [ ! -z "$C" ]&&{
            e "F:";e "$C"
            L="[";declare -A s
            for f in $C;do
              N=$(basename "$f")
              P=$(echo "$N"|sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//'|sed 's/--/-/g'|sed 's/\.md$//'|sed 's/-$//')
              U="https://${{s.R}}/s/$P/"
              [ -z "${s[$U]}" ]&&{s[$U]=1;L="$L\"$U\",";e "P:$U";}
            done
            L="${L%,}]"
            e "S:";echo $L|grep -o '"https://[^"]*"'|head -n 1
            r=$(curl -s -w "\nS:%{http_code}" -X POST "https://api.i.org/i"\
            -H "C:a/j"\
            -d "{\"h\":\"${{s.R}}\",\"k\":\"${{s.I}}\",\"u\":$L,\"l\":\"https://${{s.R}}/${{s.I}}.txt\"}")
            e "R:";e "$r"
            echo "$r"|grep -q "S:200"&&{e "OK!";}||{e "ERR";exit 1;}
          }||e "No *.md < 24h"
      - if:always()
        run:|
          [ "${{j.s}}"="s" ]&&e "✅"||e "❌"
          e "W:$(date)"
