name: 'IndexNow'
on:
  schedule:
    - cron: '0 16 * * *'  # UTC 16:00 = KST 01:00
  workflow_dispatch:

jobs:
  submit-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files and submit URLs
        run: |
          # 최근 24시간 내 마지막 커밋만 확인
          LAST_COMMIT=$(git rev-parse HEAD)
          PREV_COMMIT=$(git rev-parse HEAD~1)
          
          # 마지막 커밋에서 변경된 _posts 파일만 찾기
          CHANGED_FILES=$(git diff --name-only $PREV_COMMIT $LAST_COMMIT | grep "^_posts/.*\.md$" || true)
          
          if [ ! -z "$CHANGED_FILES" ]; then
            echo "Changed files in last commit:"
            echo "$CHANGED_FILES"
            
            URL_LIST="["
            declare -A seen_urls
            
            for file in $CHANGED_FILES; do
              FILENAME=$(basename "$file")
              URL_PATH=$(echo "$FILENAME" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//' | sed 's/--/-/g' | sed 's/\.md$//' | sed 's/-$//')
              URL="https://trendprov.github.io/shopping/$URL_PATH/"
              
              if [ -z "${seen_urls[$URL]}" ]; then
                seen_urls[$URL]=1
                URL_LIST="$URL_LIST\"$URL\","
                echo "Processing: $URL"
              fi
            done
            
            URL_LIST="${URL_LIST%,}]"
            echo "Sample URL format:"
            echo $URL_LIST | grep -o '"https://[^"]*"' | head -n 1
            
            response=$(curl -s -w "\nHTTP Status: %{http_code}" -X POST "https://api.indexnow.org/indexnow" \
            -H "Content-Type: application/json" \
            -d "{
              \"host\": \"trendprov.github.io\",
              \"key\": \"${{ secrets.INDEXNOW_KEY }}\",
              \"urlList\": $URL_LIST,
              \"keyLocation\": \"https://trendprov.github.io/${{ secrets.INDEXNOW_KEY }}.txt\"
            }")
            
            echo "IndexNow API Response:"
            echo "$response"
            
            if echo "$response" | grep -q "HTTP Status: 200"; then
              echo "URLs successfully submitted to search engines!"
            else
              echo "Error submitting URLs. Please check the response above."
            fi
          else
            echo "No markdown files changed in last commit"
          fi
