name: 'IndexNow'
on:
  schedule:
    # Set the schedule time
    - cron: '0 16 * * *'  # UTC 16시 = 한국 시간 01시

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-and-submit:
    runs-on: ubuntu-latest
    steps:
      - name: indexnow-action-bing
        uses: bojieyang/indexnow-action@v2
        with:
          sitemap-location: 'https://trendprov.github.io/sitemap.xml'
          key: ${{ secrets.INDEXNOW_KEY }}
          endpoint: 'api.indexnow.org'
