name: 'IndexNow'
on:
  schedule:
    - cron: '0 16 * * *'  # UTC 16:00 = KST 01:00
  workflow_dispatch:

jobs:
  submit-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Git Info
        run: |
          echo "===== Git Status ====="
          git status
          echo "===== Current Branch ====="
          git branch
          echo "===== Latest Commits ====="
          git log --oneline -n 5
          echo "===== Files in _posts ====="
          ls -la _posts/
          echo "===== Latest Changes ====="
          git log -p -n 1 _posts/

      - name: Get changed files and submit URLs
        run: |
          # 최근 24시간 동안의 변경사항을 직접 확인
          CHANGED_FILES=$(find _posts/ -name "*.md" -mtime -1 -type f)
          
          if [ ! -z "$CHANGED_FILES" ]; then
            echo "Changed files found:"
            echo "$CHANGED_FILES"
            
            # URL 리스트 생성
            URL_LIST="["
            declare -A seen_urls
            
            for file in $CHANGED_FILES; do
              URL_PATH=$(echo "$file" | sed -E 's/_posts\/[0-9]{4}-[0-9]{2}-[0-9]{2}-(.*)\.md/\1/')
              URL="https://trendprov.github.io/shopping/$URL_PATH/"
              
              if [ -z "${seen_urls[$URL]}" ]; then
                seen_urls[$URL]=1
                URL_LIST="$URL_LIST\"$URL\","
                echo "Processing file: $file -> $URL"
              fi
            done
            
            URL_LIST="${URL_LIST%,}]"
            echo "Submitting URLs: $URL_LIST"
            
            curl -X POST "https://api.indexnow.org/indexnow" \
            -H "Content-Type: application/json" \
            -d "{
              \"host\": \"trendprov.github.io\",
              \"key\": \"${{ secrets.INDEXNOW_KEY }}\",
              \"urlList\": $URL_LIST,
              \"keyLocation\": \"https://trendprov.github.io/${{ secrets.INDEXNOW_KEY }}.txt\"
            }"
          else
            echo "No markdown files found in _posts directory in the last 24 hours"
          fi
