name: 'IndexNow'

on:
  schedule:
    - cron: '0 16 * * *'  # UTC 16:00 = KST 01:00
  workflow_dispatch:

jobs:
  submit-urls:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Info
        run: |
          echo "Current UTC time: $(date -u)"
          echo "Current KST time: $(TZ='Asia/Seoul' date)"
          echo "Repository: ${{ github.repository }}"
          echo "Workflow triggered by: ${{ github.event_name }}"

      - name: Get changed files and submit URLs
        run: |
          CHANGED_FILES=$(find _posts/ -name "*.md" -mtime -1 -type f)
          
          if [ ! -z "$CHANGED_FILES" ]; then
            echo "Changed files found:"
            echo "$CHANGED_FILES"
            
            URL_LIST="["
            declare -A seen_urls
            
            for file in $CHANGED_FILES; do
              FILENAME=$(basename "$file")
              URL_PATH=$(echo "$FILENAME" | sed -E 's/^[0-9]{4}-[0-9]{2}-[0-9]{2}-//' | sed 's/--/-/g' | sed 's/\.md$//' | sed 's/-$//')
              URL="https://guidekey.github.io/shopping/$URL_PATH/"
              
              if [ -z "${seen_urls[$URL]}" ]; then
                seen_urls[$URL]=1
                URL_LIST="$URL_LIST\"$URL\","
                echo "Processing: $URL"
              fi
            done
            
            URL_LIST="${URL_LIST%,}]"
            echo "Sample URL format:"
            echo $URL_LIST | grep -o '"https://[^"]*"' | head -n 1
            
            response=$(curl -s -w "\nHTTP Status: %{http_code}" -X POST "https://api.indexnow.org/indexnow" \
            -H "Content-Type: application/json" \
            -d "{
              \"host\": \"guidekey.github.io\",
              \"key\": \"${{ secrets.INDEXNOW_KEY }}\",
              \"urlList\": $URL_LIST,
              \"keyLocation\": \"https://guidekey.github.io/${{ secrets.INDEXNOW_KEY }}.txt\"
            }")
            
            echo "IndexNow API Response:"
            echo "$response"
            
            if echo "$response" | grep -q "HTTP Status: 200"; then
              echo "URLs successfully submitted to search engines!"
            else
              echo "Error submitting URLs. Please check the response above."
              exit 1
            fi
          else
            echo "No markdown files found in _posts directory in the last 24 hours"
          fi

      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'IndexNow Workflow Failed',
              body: `
                Workflow failed at ${new Date().toISOString()}
                
                Repository: ${context.repo.owner}/${context.repo.repo}
                Workflow: ${context.workflow}
                Run ID: ${context.runId}
                
                Please check the Actions tab for detailed logs:
                https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}
              `
            })

      - name: Report success
        if: success()
        run: |
          echo "IndexNow submission completed successfully"
          echo "Workflow completed at: $(date)"
