name: 'IndexNow'
on:
  schedule:
    - cron: '0 16 * * *'  # UTC 16:00 = KST 01:00
  workflow_dispatch:

jobs:
  submit-urls:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 최근 커밋만 가져오기

      - name: Get recently changed files and submit URLs
        run: |
          # _posts 폴더의 .md 파일만 찾기
          CHANGED_FILES=$(git log --since="24 hours ago" --name-only --pretty=format: | grep "^_posts/.*\.md$" || true)
          
          if [ ! -z "$CHANGED_FILES" ]; then
            echo "Changed files found:"
            echo "$CHANGED_FILES"
            
            # URL 리스트 생성
            URL_LIST="["
            for file in $CHANGED_FILES; do
              # 파일명에서 날짜와 .md 제거, URL 형식으로 변환
              URL_PATH=$(echo "$file" | sed -E 's/_posts\/[0-9]{4}-[0-9]{2}-[0-9]{2}-(.*)\.md/\1/')
              URL_LIST="$URL_LIST\"https://trendprov.github.io/shopping/$URL_PATH/\","
              echo "Processing file: $file -> https://trendprov.github.io/shopping/$URL_PATH/"
            done
            URL_LIST="${URL_LIST%,}]"  # 마지막 쉼표 제거
            
            echo "Submitting URLs: $URL_LIST"
            
            # IndexNow API 호출
            curl -X POST "https://api.indexnow.org/indexnow" \
            -H "Content-Type: application/json" \
            -d "{
              \"host\": \"trendprov.github.io\",
              \"key\": \"${{ secrets.INDEXNOW_KEY }}\",
              \"urlList\": $URL_LIST,
              \"keyLocation\": \"https://trendprov.github.io/${{ secrets.INDEXNOW_KEY }}.txt\"
            }"
          else
            echo "No markdown files changed in _posts directory in the last 24 hours"
          fi
